GAngsters/config/routes.rb
Rails.application.routes.draw do
  root to: "users#new"
  get '/logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :posts do
    resources :comments, only: [:create]
  end

end

GAngsters/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

GAngsters/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

GAngsters/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :birthday, presence: true
  has_many :posts
  has_many :comments

end

GAngsters/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
   !!current_user
  end
  def authorize
    unless logged_in?
      redirect_to new_session_path
    end
  end
end

GAngsters/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to post_path(@comment.post)
  end

  def new
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

GAngsters/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = current_user.posts
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to user_path(@post.user)
    else
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
    @posts = Post.all

  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to :back
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end
  private
  def post_params
    params.require(:post).permit(:body, :user_id, :post_id, :title, :picture)
  end
end

GAngsters/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to new_post_path, notice: "Welcome OG Triple OG, Make a new Post"
    else
      flash.now.alert = "WRONG SUCKA"
      render 'new'
    end
  end

  def destroy
   session[:user_id] = nil
   redirect_to root_url, notice: "Dueces homeboy"
  end
end

GAngsters/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: :index
  def index
    @users = User.all
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts

  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :birthday)
  end
end

GAngsters/app/helpers/application_helper.rb
module ApplicationHelper
end

GAngsters/app/helpers/comments_helper.rb
module CommentsHelper
end

GAngsters/app/helpers/posts_helper.rb
module PostsHelper
end

GAngsters/app/helpers/sessions_helper.rb
module SessionsHelper
end

GAngsters/app/helpers/users_helper.rb
module UsersHelper
end

GAngsters/app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

GAngsters/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PasswordExample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <img class="ga" alt="Brand" src="http://culturelabx.com/wp-content/uploads/2014/10/general-assembly-logo.png"><span style="font-size: 40px !important; color: #000000;">ng</span>
      <div class="navbar-header">
        <a class="navbar-brand" href=""></a>
    </div>
  </div>
  </nav>
  
  <div class="container">
    <% flash.each do |name, message| %>
         <div class="flash-message flash-message-<%= name %>">
        <%= message %>
       </div>
    <% end %>
    <% if current_user %>
    <h3>Signed in as <%= current_user.name.capitalize %></h3>
    <ul class="nav nav-tabs">
      <li role="presentation"><%= link_to 'My Posts', user_path(current_user)%></li>
      <li role="presentation"><%= link_to 'New Post', new_post_path%></li>
      <li role="presentation"><%= link_to 'View Users', users_path%></li>
      <li role="presentation"><%= link_to 'Logout', session_path(session), method: :delete%></li>
    </ul>
    <%end%>

    <%= yield %>
    </form>
  </div>
</body>
</html>

GAngsters/app/views/posts/edit.html.erb
<%= form_for @post do |f|%>
<div>Body: <%= f.text_area :body %></div>
<div> <%= f.submit "Add Post" %></div>
<% end %>

GAngsters/app/views/posts/new.html.erb
<%= form_for @post do |f|%>
Title: <%= f.text_area :title, class: "form-control"%>
Body: <%= f.text_area :body, class: "form-control"%>
Picture: <%= f.text_area :picture, class: "form-control"%>
<button type="submit" class="btn btn-primary">Add Post</button>
<% end %>

GAngsters/app/views/posts/show.html.erb
  <%= image_tag(@post.picture)%>


<br>
<br>
<% @post.comments.each do |comment| %>
    <%= comment.body %>
    <%= comment.user.name.capitalize %>
    <br>
    <br>
<% end %>




<div>
  <%= form_for [@post, Comment.new] do |f| %>
      <%= f.label :body, "New comment:" %>
      <%= f.text_area :body %>
    <br>
    <button type="submit" class="btn btn-primary">Add your Comment!</button>
  <% end %>
</div>

GAngsters/app/views/users/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>GAngsters</th>
      <th>Killin it since</th>
    <tr>
      <tbody>
        <% @users.each do |u|%>
        <tr>
          <td><%= link_to "#{u.name.capitalize}", user_path(u)%></td>
          <td><%= u.birthday%></td>
          <%end%>
        </tr>
      </tbody>
    </table>

GAngsters/app/views/users/new.html.erb
<div class="col-sm-5 myUserForm">
  <div class="form-horizontal">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <!-- Name -->
      <div class="form-group">
        <%= f.label :name, class: 'col-sm-2 control-label'%>
        <div class="col-sm-10">
          <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></div>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
        </div>
        </div>
      </div>

      <!-- Birthday -->
      <div class="form-group">
        <%= f.label :birthday, class: 'col-sm-2 control-label'%>
        <div class="col-sm-10">
          <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-gift" aria-hidden="true"></span></div>
          <%= f.text_field :birthday, class: 'form-control', placeholder: 'mm/dd/yyyy' %>
        </div>
        </div>
      </div>

      <!-- Email -->
      <div class="form-group">
        <%= f.label :email, class: 'col-sm-2 control-label'%>
        <div class="col-sm-10">
          <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></div>
          <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
        </div>
        </div>
      </div>

      <!-- password -->
      <div class="form-group">
        <%= f.label :password, class: 'col-sm-2 control-label'%>
        <div class="col-sm-10">
          <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></div>
          <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
        </div>
        </div>
      </div>

      <!-- password -->
      <div class="form-group">
        <%= f.label :confirm, class: 'col-sm-2 control-label'%>
        <div class="col-sm-10">
          <div class="input-group">
          <div class="input-group-addon"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></div>
          <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Password Confirmation' %>
        </div>
        </div>
      </div>

      <button type="submit" class="btn btn-primary">Create User</button>
      <%= link_to "Already a user?", new_session_path, class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

GAngsters/app/views/users/show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= @user.name.capitalize %>'s post</th>
      <th>Delete</th>
      <th>Edit</th>
    <tr>
      <tbody>
        <% @posts.each do |post|%>
        <tr>
          <td><%= link_to post.title, post_path(post) %></td>
          <% if post.user.id == current_user.id %>
          <td><%= link_to 'Delete' , post, method: :delete%></td>
          <td><%= link_to 'Edit' , edit_post_path(post)%></td>
          <%end%>
          <%end%>
        </tr>
      </tbody>
    </table>